---
# ============================================================================
# Stage 2: Run Full Campaign (Master Orchestrator)
# ============================================================================
# Purpose: Orchestrate complete campaign lifecycle
#
# This playbook:
#   1. Records campaign start time
#   2. Calls deploy_infrastructure.yml
#   3. Calls configure_network.yml
#   4. Calls activate_attacks.yml
#   5. Monitors campaign for duration
#   6. Calls collect_data.yml
#   7. Displays completion summary
#
# Prerequisites:
#   - Stage 1 completed (Security Onion deployed and configured)
#   - Run from Security Onion
#
# Usage:
#   ansible-playbook -i inventory/hosts.yml stage2/run_full_campaign.yml
#   ansible-playbook -i inventory/hosts.yml stage2/run_full_campaign.yml -e max_student_groups=5
#
# Author: Emily Miller
# Last Updated: December 14, 2025
# ============================================================================

- name: Stage 2 - Run Full Campaign
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
  # ========================================
  # Display Campaign Information
  # ========================================

  - name: Display campaign overview
    ansible.builtin.debug:
      msg: |
        ========================================
        STAGE 2: Full Campaign Orchestration
        ========================================

        Course Information:
          - Course: {{ course_prefix }} - {{ class_name }}
          - Class Code: {{ class_code }}
          - Campaign ID: {{ campaign_id }}
          - Duration: {{ campaign_duration_hours }} hours
          - Student Groups: {{ max_student_groups }}

        Campaign Phases:
          Phase 2.1: Deploy Infrastructure
          Phase 2.2: Configure Network
          Phase 2.3: Activate Attacks
          Phase 2.4: Monitor Campaign ({{ campaign_duration_hours }} hours)
          Phase 2.5: Collect Data

        Total VMs to Deploy: {{ 3 + (max_student_groups * 5) }}

        ========================================

  - name: Record campaign start time
    ansible.builtin.set_fact:
      campaign_start_time: "{{ ansible_date_time.iso8601 }}"

  # ========================================
  # PHASE 2.1: Deploy Infrastructure
  # ========================================

  - name: Display Phase 2.1 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.1: Deploy Infrastructure
        ========================================

  #- name: Call deploy_infrastructure playbook
    #ansible.builtin.import_playbook: deploy_infrastructure.yml

  # ========================================
  # PHASE 2.2: Configure Network
  # ========================================

  - name: Display Phase 2.2 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.2: Configure Network
        ========================================

  #- name: Call configure_network playbook
    #ansible.builtin.import_playbook: configure_network.yml

  # ========================================
  # PHASE 2.3: Activate Attacks
  # ========================================

  - name: Display Phase 2.3 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.3: Activate Attacks
        ========================================

  #- name: Call activate_attacks playbook
    #ansible.builtin.import_playbook: activate_attacks.yml

  # ========================================
  # PHASE 2.4: Monitor Campaign
  # ========================================

  - name: Display Phase 2.4 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.4: Monitor Campaign
        ========================================
        Campaign will run for {{ campaign_duration_hours }} hours
        Start Time: {{ campaign_start_time }}
        ========================================

  #- name: Wait for campaign duration
    #ansible.builtin.pause:
      #seconds: "{{ campaign_duration_hours * 3600 }}"
      #prompt: "Campaign running for {{ campaign_duration_hours }} hours. Press Ctrl+C then 'C' to skip wait."

  #- name: Call monitor_campaign playbook
    #ansible.builtin.import_playbook: monitor_campaign.yml

  # ========================================
  # PHASE 2.5: Collect Data
  # ========================================

  - name: Display Phase 2.5 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.5: Collect Data
        ========================================

  #- name: Call collect_data playbook
    #ansible.builtin.import_playbook: collect_data.yml

  - name: Record campaign end time
    ansible.builtin.set_fact:
      campaign_end_time: "{{ ansible_date_time.iso8601 }}"

  # ========================================
  # Display Completion Summary
  # ========================================

  - name: Display campaign completion
    ansible.builtin.debug:
      msg: |
        ========================================
        CAMPAIGN COMPLETE
        ========================================
        
        Campaign ID: {{ campaign_id }}
        Start Time: {{ campaign_start_time }}
        End Time: {{ campaign_end_time }}
        Duration: {{ campaign_duration_hours }} hours
        
        Student Groups: {{ max_student_groups }}
        Total VMs Deployed: {{ 3 + (max_student_groups * 5) }}
        
        All phases completed successfully!
        
        Data collected and available for analysis.
        
        ========================================