---
# ============================================================================
# Stage 2: Run Full Campaign (Master Orchestrator)
# ============================================================================
# Purpose: Orchestrate complete campaign lifecycle
#
# This playbook:
#   1. Records campaign start time
#   2. Calls deploy_infrastructure.yml
#   3. Calls configure_network.yml
#   4. Calls activate_attacks.yml
#   5. Monitors campaign for duration
#   6. Calls collect_data.yml
#   7. Displays completion summary
#
# Prerequisites:
#   - Stage 1 completed (Security Onion deployed and configured)
#   - Run from Security Onion
#
# Usage:
#   ansible-playbook -i inventory/hosts.yml stage2/run_full_campaign.yml
#   ansible-playbook -i inventory/hosts.yml stage2/run_full_campaign.yml -e max_student_groups=5
#
# Author: Emily Miller
# Last Updated: December 22, 2025
# ============================================================================

# ============================================================================
# PLAY 1: Campaign Setup
# ============================================================================
- name: Campaign Setup
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
  - name: Display campaign overview
    ansible.builtin.debug:
      msg: |
        ========================================
        STAGE 2: Full Campaign Orchestration
        ========================================

        Course Information:
          - Course: {{ course_prefix }} - {{ class_name }}
          - Class Code: {{ class_code }}
          - Campaign ID: {{ campaign_id }}
          - Duration: {{ campaign_duration_hours }} hours
          - Student Groups: {{ max_student_groups }}

        Campaign Phases:
          Phase 2.1: Deploy Infrastructure
          Phase 2.2: Configure Network
          Phase 2.3: Activate Attacks
          Phase 2.4: Monitor Campaign ({{ campaign_duration_hours }} hours)
          Phase 2.5: Collect Data

        Total VMs to Deploy: {{ 3 + (max_student_groups * 5) }}

        ========================================

  - name: Record campaign start time
    ansible.builtin.set_fact:
      campaign_start_time: "{{ ansible_date_time.iso8601 }}"
      campaign_start_epoch: "{{ ansible_date_time.epoch }}"

  - name: Display Phase 2.1 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.1: Deploy Infrastructure
        ========================================

# ============================================================================
# PLAY 2: Import Phase 2.1 - Deploy Infrastructure
# ============================================================================
- import_playbook: deploy_infrastructure.yml

# ============================================================================
# PLAY 3: Phase 2.2 Notice
# ============================================================================
- name: Phase 2.2 Notice
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Display Phase 2.2 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.2: Configure Network
        ========================================

# ============================================================================
# PLAY 4: Import Phase 2.2 - Configure Network
# ============================================================================
#- import_playbook: configure_network.yml

# ============================================================================
# PLAY 5: Phase 2.3 Notice
# ============================================================================
- name: Phase 2.3 Notice
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Display Phase 2.3 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.3: Activate Attacks
        ========================================

# ============================================================================
# PLAY 6: Import Phase 2.3 - Activate Attacks
# ============================================================================
#- import_playbook: activate_attacks.yml

# ============================================================================
# PLAY 7: Phase 2.4 - Monitor Campaign
# ============================================================================
- name: Phase 2.4 - Monitor Campaign
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
  - name: Display Phase 2.4 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.4: Monitor Campaign
        ========================================
        Campaign will run for {{ campaign_duration_hours }} hours
        Start Time: {{ campaign_start_time }}
        ========================================

  #- name: Wait for campaign duration
    #ansible.builtin.pause:
      #seconds: "{{ campaign_duration_hours * 3600 }}"
      #prompt: "Campaign running for {{ campaign_duration_hours }} hours. Press Ctrl+C then 'C' to skip wait."

# ============================================================================
# PLAY 8: Import Phase 2.4 - Monitor Campaign
# ============================================================================
#- import_playbook: monitor_campaign.yml

# ============================================================================
# PLAY 9: Phase 2.5 Notice
# ============================================================================
- name: Phase 2.5 Notice
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Display Phase 2.5 notice
    ansible.builtin.debug:
      msg: |
        ========================================
        PHASE 2.5: Collect Data
        ========================================

# ============================================================================
# PLAY 10: Import Phase 2.5 - Collect Data
# ============================================================================
#- import_playbook: collect_data.yml

# ============================================================================
# PLAY 11: Stage 2 Completion
# ============================================================================
- name: Stage 2 Completion
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Display Stage 2 completion
    ansible.builtin.debug:
      msg: |
        ========================================
        STAGE 2 COMPLETE
        ========================================
        
        Campaign Run Successfully
        
        ========================================
