---
# Ansible playbook to create and boot a single VM from a template in Proxmox VE

- name: Create and boot a single VM from a template
  hosts: localhost
  gather_facts: false

  vars:
    # --- Proxmox API ---
    api_host: "192.168.68.89"
    api_user: "root@pam"
    api_password: "K!CsBRyr&~<Lq1S5_8Z{"
    node: "hm-hcr-08"

    # --- Inputs ---
    course_prefix: "CIS4416"
    target_storage: "raid-lvm"
    ovf_path: "/mnt/pve/ovfstore/*.ovf"

    # --- Group -> bridge (default G1) ---
    bridge_by_group:
      G1: "vmbr80"
      G2: "vmbr90"
    lab_group: "G1"

    # Base VMID calculation (bridge number ×100)
    vmid_base: "{{ (bridge_by_group[lab_group] | regex_search('\\d+') | int) * 100 }}" # e.g., 80*100=8000
    bridge_name: "{{ bridge_by_group[lab_group] }}" # e.g., vmbr80

  tasks:
    # --- OVF File Handling ---
    - name: Find OVF files on node
      ansible.builtin.shell: "ls -1 {{ ovf_path }} 2>/dev/null || true" # avoid error if none found
      register: ovf_list # list of OVF files
      changed_when: false # not changing system state
      delegate_to: "{{ node }}" # run on Proxmox node

    - name: Ensure at least one OVF file was found
      ansible.builtin.fail:
        msg: "No OVF files found in {{ ovf_path }}" # error message
      when: ovf_list.stdout_lines | length == 0 # check if list is empty

    - name: Set first OVF file as selected template
      ansible.builtin.set_fact:
        ovf_file: "{{ ovf_list.stdout_lines[0] }}" # first OVF file

    # --- Pull info from file name & compute IDs ---
    - name: Derive VMID and name from inputs
      ansible.builtin.set_fact:
        vmid: "{{ vmid_base + 1 }}"
        vm_seq: "{{ '%02d' | format((vmid_base + 1) % 100) }}" # sequence number within group
        _base: "{{ ovf_file | basename | regex_replace('\\.ovf$', '') | regex_replace('^TEMPLATE-', '') }}" # base name
        ovf_token: "{{ _base.split('-')[0] | title }}" # token from filename
        vm_name: "{{ course_prefix }} {{ ovf_token }} {{ vm_seq }}" # final VM name

    # --- Create VM (SeaBIOS flow only) ---
    - name: Import OVF (creates VM once) #importovf replacement
      ansible.builtin.command: >
        qm importovf {{ vmid }} "{{ ovf_file }}" {{ target_storage }}
      args:
        creates: "/etc/pve/qemu-server/{{ vmid }}.conf" # only run if VM config doesn't exist
      delegate_to: "{{ node }}" # run on Proxmox node

    - name: Check if scsi0 already attached
      ansible.builtin.shell: "qm config {{ vmid }} | grep -E '^scsi0:'" # check for scsi0
      register: scsi0_present # register result
      changed_when: false # not changing system state
      failed_when: false   # avoid failure if not found
      delegate_to: "{{ node }}" # run on Proxmox node

    - name: Attach disk to SCSI controller (virtio-scsi + scsi0) if missing #attach scsi
      ansible.builtin.command: >
        qm set {{ vmid }} --scsihw virtio-scsi-pci --scsi0 {{ target_storage }}:vm-{{ vmid }}-disk-0
      when: scsi0_present.rc != 0 # only if scsi0 not found
      delegate_to: "{{ node }}" # run on Proxmox node

    - name: Force legacy BIOS (SeaBIOS) and set boot order #bios set and boot order
      ansible.builtin.shell: |
        qm set {{ vmid }} --bios seabios
        qm set {{ vmid }} --boot order=scsi0
      args:
        warn: false # suppress warnings
      delegate_to: "{{ node }}" # run on Proxmox node

    # --- Name + NIC via API ---
    - name: Configure name and NIC on the group bridge (e1000 + firewall=1)
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}" # Proxmox API host
        api_user: "{{ api_user }}" # Proxmox API user
        api_password: "{{ api_password }}" # Proxmox API password
        node: "{{ node }}" # Proxmox node
        vmid: "{{ vmid }}" # VM ID
        name: "{{ vm_name }}" # VM name
        net0: "e1000,bridge={{ bridge_name }},firewall=1" # NIC config
        state: present  # ensure VM is present

    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"  # Proxmox API host
        api_user: "{{ api_user }}"  # Proxmox API user
        api_password: "{{ api_password }}" # Proxmox API password
        node: "{{ node }}"  # Proxmox node
        vmid: "{{ vmid }}"  # VM ID
        state: started  # ensure VM is started
