---
###############################################################################
# Master Experiment Playbook
# University of West Florida
# Orchestrated Generation of Correlated Host and Network-Based Datasets for Advanced Threat Detection
#
# Purpose: Orchestration of the entire experiment from network setup to data collection/teardown.
# Author: Emily Miller
# Last Updated: December 21, 2025
#
# This playbook runs the complete pipeline in sequence:
#   Stage 0: Network topology and VM template preparation
#   Stage 1: Security Onion deployment and configuration
#   Stage 2: Student environment deployment and configuration
#
# Usage:
#   ansible-playbook -i inventory/hosts.yml run_full_experiment.yml
#
###############################################################################

- name: "Display Experiment Start"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display execution plan
      debug:
        msg:
          - "╔═════════════════════════════════════════════╗"
          - "║         CYBER RANGE FULL EXPERIMENT         ║"
          - "╚═════════════════════════════════════════════╝"
          - ""
          - "This playbook will execute the following stages in sequence:"
          - "  1. Stage 0: Network Topology"
          - "  2. Stage 1: Security Onion Deployment and Configuration"
          - "  3. Stage 2: Experiment Environment Deployment and Configuration"
          - ""

###############################################################################
# STAGE 0: Network Topology and VM Template Preparation
###############################################################################
- name: "Stage 0 - Network Topology Setup"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 0 start
      debug:
        msg: ">>> Starting Stage 0: Network Topology and Template Setup"

- import_playbook: stage0/stage0_configure_proxmox_network.yml

- name: "Stage 0 Complete"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 0 completion
      debug:
        msg: "✓ Stage 0 Complete: Network topology and templates ready"

###############################################################################
# STAGE 1: Security Onion Deployment and Configuration
###############################################################################
- name: "Stage 1 - Security Onion Deployment"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 1 start
      debug:
        msg: ">>> Starting Stage 1: Security Onion Deployment"

- import_playbook: stage1/stage1_bootstrap_security_onion.yml

- name: "Stage 1 Complete"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 1 completion
      debug:
        msg: "✓ Stage 1 Complete: Security Onion monitoring active"

###############################################################################
# STAGE 2: Student Environment Deployment
###############################################################################
- name: "Stage 2 - Student Environment Deployment"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 2 start
      debug:
        msg: ">>> Starting Stage 2: Student Environment Deployment"

- import_playbook: stage2/run_full_campaign.yml

- name: "Stage 2 Complete"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 2 completion
      debug:
        msg: "✓ Stage 2 Complete: Experiment Complete"

###############################################################################
# CLEANUP: Experiment Cleanup and Teardown
###############################################################################
#- name: "Cleanup - Experiment Cleanup and Teardown"
  #hosts: localhost
  #gather_facts: no
  #tasks:
    - #name: Display Cleanup start
      #debug:
        #msg: ">>> Starting Cleanup: Experiment Cleanup and Teardown"

#- import_playbook: stage2/teardown.yml

#- name: "Cleanup Complete"
  #hosts: localhost
  #gather_facts: no
  #tasks:
    #- name: Display Cleanup completion
      #debug:
        #msg: "✓ Cleanup Complete: Experiment Cleanup and Teardown Complete"

###############################################################################
# Completion Summary
###############################################################################
- name: "Experiment Complete"
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Record experiment end time
      ansible.builtin.set_fact:
        experiment_end_time: "{{ ansible_date_time.iso8601 }}"
        experiment_end_epoch: "{{ ansible_date_time.epoch }}"

    - name: Calculate actual experiment duration
      set_fact:
        actual_duration_seconds: "{{ experiment_end_epoch | int - hostvars['localhost']['campaign_start_epoch'] | default(experiment_end_epoch) | int }}"
        actual_duration_hours: "{{ ((experiment_end_epoch | int - hostvars['localhost']['campaign_start_epoch'] | default(experiment_end_epoch) | int) / 3600) | round(2) }}"
      when: hostvars['localhost']['campaign_start_epoch'] is defined

    - name: Display detailed experiment summary
      debug:
        msg:
          - ""
          - "╔═════════════════════════════════════════════════════════╗"
          - "║              EXPERIMENT EXECUTION COMPLETE              ║"
          - "╚═════════════════════════════════════════════════════════╝"
          - ""
          - "Campaign Information:"
          - "  Campaign ID: {{ campaign_id | default('N/A') }}"
          - "  Start Time: {{ hostvars['localhost']['campaign_start_time'] | default('N/A') }}"
          - "  End Time: {{ experiment_end_time }}"
          - "  Duration: {{ actual_duration_hours | default('N/A') }} hours"
          - ""
          - "Infrastructure Deployed:"
          - "  Student Groups: {{ max_student_groups | default(0) }}"
          - "  Total VMs: {{ 3 + (max_student_groups | default(0) | int * 5) }}"
          - "    - Spark pfSense: 1"
          - "    - Instructor pfSense: 1"
          - "    - Instructor Kali: 1"
          - "    - Student pfSense VMs: {{ max_student_groups | default(0) }}"
          - "    - Student Kali VMs: {{ max_student_groups | default(0) * 2 }}"
          - "    - Student Metasploitable VMs: {{ max_student_groups | default(0) * 2 }}"
          - ""
          - "Phases Completed:"
          - "  ✓ Stage 0: Network Topology Setup"
          - "  ✓ Stage 1: Security Onion Deployment"
          - "  ✓ Stage 2: Campaign Execution"
          - ""
          - "All stages completed successfully!"
          - "Data Ready for Analysis."
          - ""
