---
###############################################################################
# Simple Master Experiment Playbook
# University of West Florida - Cyber War Gaming Course
# Automated Cyber Range for Threat Detection Dataset Generation
#
# Purpose: Simple orchestration of all three automation stages
# Author: Emily Miller
# Last Updated: December 21, 2025
#
# This playbook runs the complete pipeline in sequence:
#   Stage 0: Network topology and VM template preparation
#   Stage 1: Security Onion deployment and configuration
#   Stage 2: Student environment deployment and configuration
#
# Usage:
#   ansible-playbook -i inventory/hosts.yml run_full_experiment.yml
#
###############################################################################

- name: "Display Experiment Start"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display execution plan
      debug:
        msg:
          - "╔══════════════════════════════════════════════════════════════════╗"
          - "║         CYBER RANGE FULL EXPERIMENT - SIMPLE MODE               ║"
          - "╚══════════════════════════════════════════════════════════════════╝"
          - ""
          - "This playbook will execute the following stages in sequence:"
          - "  1. Stage 0: Network Topology"
          - "  2. Stage 1: Security Onion Deployment and Configuration"
          - "  3. Stage 2: Experiment Environment Deployment and Configuration"
          - ""

###############################################################################
# STAGE 0: Network Topology and VM Template Preparation
###############################################################################
- name: "Stage 0 - Network Topology Setup"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 0 start
      debug:
        msg: ">>> Starting Stage 0: Network Topology and Template Setup"

- import_playbook: stage0/stage0_configure_proxmox_network.yml

- name: "Stage 0 Complete"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 0 completion
      debug:
        msg: "✓ Stage 0 Complete: Network topology and templates ready"

###############################################################################
# STAGE 1: Security Onion Deployment and Configuration
###############################################################################
- name: "Stage 1 - Security Onion Deployment"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 1 start
      debug:
        msg: ">>> Starting Stage 1: Security Onion Deployment"

- import_playbook: stage1/stage1_bootstrap_security_onion.yml

- name: "Stage 1 Complete"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 1 completion
      debug:
        msg: "✓ Stage 1 Complete: Security Onion monitoring active"

###############################################################################
# STAGE 2: Student Environment Deployment
###############################################################################
- name: "Stage 2 - Student Environment Deployment"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 2 start
      debug:
        msg: ">>> Starting Stage 2: Student Environment Deployment"

- import_playbook: stage2/run_full_campaign.yml

- name: "Stage 2 Complete"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display Stage 2 completion
      debug:
        msg: "✓ Stage 2 Complete: Student environments deployed"

###############################################################################
# Completion Summary
###############################################################################
- name: "Experiment Complete"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display final summary
      debug:
        msg:
          - ""
          - "╔══════════════════════════════════════════════════════════════════╗"
          - "║              EXPERIMENT EXECUTION COMPLETE                       ║"
          - "╚══════════════════════════════════════════════════════════════════╝"
          - ""
          - "All stages completed successfully!"
          - ""
