---
# ============================================================================
# Ansible Inventory for Cyber Range Automation
# ============================================================================
# Minimal inventory containing only hosts needed for Stage 0 and Stage 1
#
# Stage 0: Configure Proxmox network bridges
# Stage 1: Deploy Security Onion VM
#
# Usage:
#   ansible-playbook -i inventory/hosts.yml stage0_configure_proxmox_network.yml
#   ansible-playbook -i inventory/hosts.yml stage1_bootstrap_security_onion.yml
#
# Note: Additional hosts (Security Onion, student VMs, instructor VMs) will
# be added in later stages as they are deployed and become accessible.
# ============================================================================

all:
  children:
    # ========================================
    # Control Node (where playbooks execute)
    # ========================================
    control_node:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    # ========================================
    # Proxmox VE Host
    # ========================================
    pve:
      hosts:
        hm-hcr-08:
          ansible_host: 192.168.68.89
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
