---
all:
  children:
    # ========================================
    # Control Node (where playbooks execute)
    # ========================================
    control_node:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    # ========================================
    # Proxmox VE Host
    # ========================================
    pve:
      hosts:
        hm-hcr-08:
          ansible_host: 192.168.68.89
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
