---
- name: Deploy and run nmap script from control node Desktop on Kali VM, fetch results
  hosts: kali
  gather_facts: yes
  vars:
    # Path to script on the control node (Ubuntu Desktop)
    local_script_path: "/home/ubuntu/Desktop/Automated Exploits/Automated Exploits/nmapScript.sh"

    # Remote paths on Kali
    remote_home: /home/kali
    remote_script: "{{ remote_home }}/run_nmap.sh"
    remote_csv: "{{ remote_home }}/nmap_scan.csv"
    remote_xml: "{{ remote_home }}/nmapOut.xml"

    # Where to save fetched files on the control node (Desktop folder named "script outputs")
    local_fetch_dir: "{{ lookup('env','HOME') }}/Desktop/script outputs"

  tasks:
  # Check for local script presence
    - name: Fail early if local script doesn't exist (control node)
      delegate_to: localhost
      stat:
        path: "{{ local_script_path }}"
      register: local_script_stat
  
  # Abort if script not found
    - name: Abort if script not found on Desktop
      delegate_to: localhost
      fail:
        msg: "Local script not found at {{ local_script_path }} — place run_nmap.sh on your Ubuntu Desktop or change local_script_path."
      when: not local_script_stat.stat.exists
  
  # Ensure nmap installed on Kali
    - name: Ensure nmap is installed on Kali (Debian family)
      become: yes
      apt:
        name: nmap
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
  
  # Ensure remote home exists
    - name: Ensure remote home exists
      become: yes
      file:
        path: "{{ remote_home }}"
        state: directory
        owner: kali
        group: kali
        mode: '0755'
  
  # Copy script to Kali
    - name: Copy nmap script from control node Desktop to Kali
      become: yes
      copy:
        src: "{{ local_script_path }}"    # from control node
        dest: "{{ remote_script }}"      # on Kali
        owner: kali
        group: kali
        mode: '0755'
  
  # Ensure CSV exists or create new one
    - name: Ensure CSV exists (create if missing) and owned by kali
      become: yes
      file:
        path: "{{ remote_csv }}"
        state: touch
        owner: kali
        group: kali
        mode: '0644'
  
  # Run the nmap script
    - name: Run the nmap script on Kali (cwd = /home/kali) as user kali
      become: yes
      become_user: kali
      shell: "{{ remote_script }}"
      args:
        chdir: "{{ remote_home }}"
      register: run_result
      #rc==0 as success; script returns 0 on success
      changed_when: run_result.rc == 0
  
  # Check for result files
    - name: Check for remote nmap XML file on Kali
      stat:
        path: "{{ remote_xml }}"
      register: remote_xml_stat

    - name: Check for remote nmap CSV file on Kali
      stat:
        path: "{{ remote_csv }}"
      register: remote_csv_stat

    - name: Show whether XML/CSV were created on the remote host
      debug:
        msg:
          - "XML exists: {{ remote_xml_stat.stat.exists | default(false) }}"
          - "CSV exists: {{ remote_csv_stat.stat.exists | default(false) }}"
      changed_when: false
  
  # Fetch result files to control node
    - name: Ensure local fetch subdirectory exists for this host (control node)
      delegate_to: localhost
      file:
        path: "{{ local_fetch_dir }}/{{ inventory_hostname }}"
        state: directory
        mode: '0755'

    - name: Fetch nmap XML result if present
      fetch:
        src: "{{ remote_xml }}"
        dest: "{{ local_fetch_dir }}/{{ inventory_hostname }}/"
        flat: yes
      when: remote_xml_stat.stat.exists

    - name: Fetch CSV results if present
      fetch:
        src: "{{ remote_csv }}"
        dest: "{{ local_fetch_dir }}/{{ inventory_hostname }}/"
        flat: yes
      when: remote_csv_stat.stat.exists